<?php
/**
 * Created by PhpStorm.
 * User: tianya
 * Date: 2016/12/25
 * Time: 12:57
 * 基础控制器
 */

namespace frontend\controllers\base;


use yii\web\Controller;

class BaseController extends Controller
{
    public function beforeAction($action)
    {
        if(!parent::beforeAction($action)){
            return false;
        } // TODO: Change the autogenerated stub
        return true;
    }
}